Repository PuzzleShare/puzzle_share, pull requests merged in 2024-11, with the labels that each got.

#2 [ALL] 프로젝트 준비를 위해 깃허브 세팅하였습니다.
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: ⚙️ 환경설정, 📑 문서, :sparkles: ALL

#4 [BE] spring boot 환경을 세팅한다.
  backend/.gitattributes
  backend/.gitignore
  backend/build.gradle.kts
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle.kts
  backend/src/main/kotlin/com/puzzle/backend/BackendApplication.kt
  backend/src/main/resources/application.yaml
  backend/src/test/kotlin/com/puzzle/backend/BackendApplicationTests.kt
Labels: ⚙️ 환경설정, 🍃 백엔드

#6 [FE] react 환경 설정
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/tsconfig.json
Labels: ⚙️ 환경설정, 💻 프론트엔드

#8 [BE] 웹소켓 서버 환경을 세팅한다
  websocket/.gitattributes
  websocket/.gitignore
  websocket/build.gradle.kts
  websocket/gradle/wrapper/gradle-wrapper.jar
  websocket/gradle/wrapper/gradle-wrapper.properties
  websocket/gradlew
  websocket/gradlew.bat
  websocket/settings.gradle.kts
  websocket/src/main/kotlin/com/puzzle/websocket/WebsocketApplication.kt
  websocket/src/main/resources/application.properties
  websocket/src/test/kotlin/com/puzzle/websocket/WebsocketApplicationTests.kt
Labels: ⚙️ 환경설정, 🍃 백엔드

#24 [BE] 자동 배포 기능 구현
  .github/workflows/backend-cd.yml
  backend/Dockerfile
  backend/container.template.json
Labels: ⚙️ 환경설정, 🍃 백엔드

#37 [BE] 퍼즐 로직 병합
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/Command.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/PuzzleBoard.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/Team.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/User.kt
Labels: 💡 기능, :sparkles: ALL

#42 [BE] 게임 대기방 SOCKET 기능 구현
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomController.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/RoomListResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/WaitingRoomResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  websocket/build.gradle.kts
  websocket/src/main/kotlin/com/puzzle/websocket/common/BaseResponse.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/config/RedisConfig.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/config/WebSocketConfig.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/exception/CustomExceptionHandler.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/exception/custom/NoneMasterException.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/exception/custom/RoomFullException.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/status/EnumStatus.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/controller/PuzzleController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/controller/PuzzleRoomController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/domain/Player.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/domain/PuzzleRoom.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/request/RoomIdRequest.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/response/RoomIdResponse.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/repository/PlayerRepository.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/repository/PuzzleRoomRepository.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/service/PuzzleRoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/service/PuzzleRoomServiceImpl.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/service/PuzzleServiceImpl.kt
  websocket/src/main/resources/application.yaml
  websocket/src/main/resources/static/puzzleRoomList.html
  websocket/src/main/resources/static/puzzleWatingRoom.html
Labels: 🍃 백엔드

#48 [BE] swagger 도입
  .github/workflows/backend-ci.yml
  backend/build.gradle.kts
  backend/src/main/kotlin/com/puzzle/backend/common/config/ApiDocsConfig.kt
  backend/src/main/kotlin/com/puzzle/backend/common/config/SecurityConfig.kt
  backend/src/main/kotlin/com/puzzle/backend/common/controller/TestController.kt
  backend/src/main/kotlin/com/puzzle/backend/common/controller/TestControllerSpec.kt
  backend/src/main/kotlin/com/puzzle/backend/common/oauth/controller/UsersController.kt
  backend/src/main/kotlin/com/puzzle/backend/common/oauth/controller/UsersControllerSpec.kt
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomController.kt
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomControllerSpec.kt
  backend/src/main/resources/application-docs.yml
  backend/src/main/resources/application.yml
Labels: ⚙️ 환경설정, 🍃 백엔드

#55 [BE] 게임 방 소켓
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Player.kt
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/PlayerRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/RoomListResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/WaitingRoomResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/repository/PlayerRepository.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/config/CorsConfig.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/config/MyWebSocketHandler.kt
  websocket/src/main/kotlin/com/puzzle/websocket/common/config/WebSocketConfig.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/controller/PuzzleRoomController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/domain/Player.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/domain/PuzzleRoom.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/dto/request/PlayerRequest.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/repository/PlayerRepository.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/service/PuzzleRoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/service/PuzzleRoomServiceImpl.kt
  websocket/src/main/resources/application.yaml
Labels: 🍃 백엔드

#58 [BE] 대기방 버그 수정
  websocket/src/main/kotlin/com/puzzle/websocket/common/config/CorsConfig.kt
  websocket/src/main/kotlin/com/puzzle/websocket/puzzle/service/PuzzleRoomServiceImpl.kt
Labels: 🚨 버그, 🍃 백엔드

#59 [BE] roomList data nullPointerException 처리
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
Labels: 🚨 버그, 🍃 백엔드

#64 [BE] 게임 플레이
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Team.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/service/GameService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/domain/PuzzleRoom.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomServiceImpl.kt
Labels: 🍃 백엔드

#83 [BE] timer 기능 살리기
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/PuzzleBoard.kt
Labels: 🍃 백엔드

#90 [BE] 문법 수정
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
Labels: 🚨 버그, 🍃 백엔드

#106 [BE] 게임 이미지 custom 적용
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Picture.kt
Labels: 🍃 백엔드

#122 [BE] 친구 추가/제거 기능 api
  backend/src/main/kotlin/com/puzzle/backend/friend/controller/FriendController.kt
  backend/src/main/kotlin/com/puzzle/backend/friend/domain/Friend.kt
  backend/src/main/kotlin/com/puzzle/backend/friend/repository/FriendRepository.kt
  backend/src/main/kotlin/com/puzzle/backend/friend/service/FriendService.kt
  backend/src/main/resources/db/migration/V2__friend.sql
Labels: 🍃 백엔드

#125 [BE] 진행률 로직 수정
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Piece.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/PuzzleBoard.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/ResponseMessage.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/service/GameService.kt
Labels: 🍃 백엔드

#138 [BE] redis 데이터 마이그레이션 작업
  websocket/build.gradle.kts
  websocket/src/main/kotlin/com/puzzle/websocket/common/config/RedisConfig.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/ListStringUtils.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Picture.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/PuzzleBoard.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/service/GameService.kt
Labels: 🍃 백엔드, 💡 기능

#120 feat : 게임 전적 도메인 추가
  backend/src/main/kotlin/com/puzzle/backend/common/config/SecurityConfig.kt
  backend/src/main/kotlin/com/puzzle/backend/oauth/domain/Users.kt
  backend/src/main/kotlin/com/puzzle/backend/record/controller/GameRecordController.kt
  backend/src/main/kotlin/com/puzzle/backend/record/domain/GameRecord.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameDataDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameRecordDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/repository/GameRecordRepository.kt
  backend/src/main/kotlin/com/puzzle/backend/record/service/GameRecordService.kt
  backend/src/main/resources/db/migration/V3__update_users_table.sql
  backend/src/main/resources/db/migration/V4__create_game_records_table.sql
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/GameType.kt
Labels: 🍃 백엔드

#143 [BE] 게임 대기룸 친구 및 사용자 초대
  backend/src/main/kotlin/com/puzzle/backend/friend/controller/FriendController.kt
  backend/src/main/kotlin/com/puzzle/backend/friend/dto/response/FriendDataResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/friend/repository/FriendRepository.kt
  backend/src/main/kotlin/com/puzzle/backend/friend/service/FriendService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/controller/PuzzleRoomController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/dto/request/InviteRequest.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomServiceImpl.kt
Labels: 🍃 백엔드

#153 [BE] 사용자 검색 기능 구현
  backend/src/main/kotlin/com/puzzle/backend/friend/controller/FriendController.kt
  backend/src/main/kotlin/com/puzzle/backend/friend/service/FriendService.kt
  backend/src/main/kotlin/com/puzzle/backend/oauth/repository/UsersRepository.kt
Labels: 🍃 백엔드

#161 [BE] 방장만 gameStart 실행 가능
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomServiceImpl.kt
Labels: 🍃 백엔드

#159 feat : 커스텀 이미지 기능
  backend/.gitignore
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomController.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  backend/src/main/resources/application.yml
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/ImageDimensionDto.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Picture.kt
Labels: 🍃 백엔드, 💡 기능

#163 [스프린트4-1] 방장만 gamestart, 커스텀 그림
  backend/.gitignore
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomController.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  backend/src/main/resources/application.yml
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/ImageDimensionDto.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Picture.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/PuzzleBoard.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/service/GameService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomServiceImpl.kt
Labels: 🍃 백엔드, 🚛배포

#172 [스프린트4] 게임방 페이지 제거
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomController.kt
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomControllerSpec.kt
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/RoomListResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  backend/src/main/resources/application.yml
  websocket/src/main/kotlin/com/puzzle/websocket/room/domain/PuzzleRoom.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomServiceImpl.kt
Labels: 🍃 백엔드, 💡 기능

#173 [BE] 마이 페이지에서 게임 전적 조회 기능 - 배틀 모드
  backend/src/main/kotlin/com/puzzle/backend/oauth/domain/Users.kt
  backend/src/main/kotlin/com/puzzle/backend/record/controller/GameRecordController.kt
  backend/src/main/kotlin/com/puzzle/backend/record/domain/GameRecord.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameDataDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameRecordDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/UserGameRecordsResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/record/repository/GameRecordRepository.kt
  backend/src/main/kotlin/com/puzzle/backend/record/service/GameRecordService.kt
  backend/src/main/resources/db/migration/V5__update_game_records_table.sql
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/service/GameService.kt
Labels: 🍃 백엔드

#176 [BE] 퍼즐 진행률 로직 수정
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/PuzzleBoard.kt
Labels: 🍃 백엔드

#181 [BE] 커스텀 이미지 webp 추가
  backend/build.gradle.kts
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  websocket/build.gradle.kts
  websocket/src/main/kotlin/com/puzzle/websocket/WebsocketApplication.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Picture.kt
Labels: 🍃 백엔드, 💡 기능

#189 fix : 서버 도메인, 프론트 도메인 수정
  backend/src/main/kotlin/com/puzzle/backend/common/config/CorsConfig.kt
  backend/src/main/kotlin/com/puzzle/backend/oauth/service/JwtProvider.kt
  backend/src/main/resources/application-dev.yml
Labels: ⚙️ 환경설정, 🍃 백엔드

#190 [ALL] 깃허브 세팅 변경
  .github/ISSUE_TEMPLATE/bug_report.md
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/tsconfig.json
Labels: ⚙️ 환경설정, :sparkles: ALL
