Repository PuzzleShare/puzzle_share, pull requests merged in 2024-12, with the labels that each got.

#193 [ALL] 퍼즐 진행률 100퍼센트가 되었을 때만 gallery에 해당 사진 추가
  backend/src/main/kotlin/com/puzzle/backend/record/controller/GameRecordController.kt
  backend/src/main/kotlin/com/puzzle/backend/record/domain/GameRecord.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameDataDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameRecordDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/UserGalleryResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/record/repository/GameRecordRepository.kt
  backend/src/main/kotlin/com/puzzle/backend/record/service/GameRecordService.kt
  backend/src/main/resources/db/migration/V6__update_game_records_table.sql
Labels: :sparkles: ALL

#194 [BE] 방 생성시 시간 선택과 퍼즐 조각 수 확인
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomController.kt
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Room.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/domain/PuzzleRoom.kt
Labels: 🍃 백엔드, 💡 기능

#195 [BE] 방상태 room 엔터티 roomStatus(대기,게임중) 추가
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/RoomListResponse.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/domain/PuzzleRoom.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomServiceImpl.kt
Labels: 🍃 백엔드

#202 [BE] 대기룸 생성순으로 정렬
  backend/src/main/kotlin/com/puzzle/backend/oauth/service/JwtProvider.kt
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/WaitingRoomResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
Labels: 🍃 백엔드

#205 [BE] 갤러리 게임 플레이어들 수정
  backend/src/main/kotlin/com/puzzle/backend/record/domain/GameRecord.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameDataDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameRecordDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/UserGalleryResponse.kt
  backend/src/main/resources/db/migration/V7__add_game_records_table.sql
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/ResponseMessage.kt
Labels: 🍃 백엔드

#207 [BE] 방 대기 리스트 오름차순 -> 내림차순
  backend/src/main/kotlin/com/puzzle/backend/record/domain/GameRecord.kt
  backend/src/main/kotlin/com/puzzle/backend/record/dto/GameRecordDto.kt
  backend/src/main/kotlin/com/puzzle/backend/record/repository/GameRecordRepository.kt
  backend/src/main/kotlin/com/puzzle/backend/record/service/GameRecordService.kt
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/RoomListResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
Labels: 🍃 백엔드

#209 refactor : 이미지 길이 측정은 backend로 통일
  backend/src/main/kotlin/com/puzzle/backend/common/exception/CustomExceptionHandler.kt
  backend/src/main/kotlin/com/puzzle/backend/common/exception/custom/ImageValidationException.kt
  backend/src/main/kotlin/com/puzzle/backend/oauth/domain/Users.kt
  backend/src/main/kotlin/com/puzzle/backend/room/controller/RoomController.kt
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/ImageResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Picture.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/domain/PuzzleRoom.kt
  websocket/src/main/kotlin/com/puzzle/websocket/temp/TempController.kt
Labels: 🍃 백엔드, 🔨 리팩터링

#212 feat : 방삭제
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Picture.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/service/GameService.kt
Labels: 🍃 백엔드, 🔨 리팩터링

#218 fix : 방생성시 이미지 확인 로직 변경
  backend/src/main/kotlin/com/puzzle/backend/room/domain/Room.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/request/CreateRoomRequest.kt
  backend/src/main/kotlin/com/puzzle/backend/room/service/RoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/domain/Game.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/domain/PuzzleRoom.kt
Labels: 🍃 백엔드, 💡 기능

#220 [BE] 게임중 상대팀 나갈 때 게임 종료
  websocket/src/main/kotlin/com/puzzle/websocket/game/controller/GameController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/game/service/GameService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/controller/PuzzleRoomController.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomService.kt
  websocket/src/main/kotlin/com/puzzle/websocket/room/service/PuzzleRoomServiceImpl.kt
Labels: 🍃 백엔드

#223 [BE] 게임 목록 및 대기방에 BATTLE, 대전모드 변경을 위한 response 수정
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/RoomListResponse.kt
  backend/src/main/kotlin/com/puzzle/backend/room/dto/response/WaitingRoomResponse.kt
Labels: 🍃 백엔드
